import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Table from "@/components/Table";
import axios from "axios";

export default function Home({ exchangesData }) {
  return (
    <>
      <Head>
        <title>Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>Cryptocurrency exchanges</header>

      <Table exchangesData={exchangesData} />
    </>
  );
}

export async function getStaticProps() {
  async function getExchangesData() {
    try {
      const response = await axios.get(
        "https://api.coingecko.com/api/v3/exchanges"
      );

      return response.data;
    } catch (error) {
      console.error(error);
    }
  }

  const exchangesData = await getExchangesData();

  return {
    props: {
      exchangesData,
    },
  };
}
